remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Josh Madrone's IT Blog
subtitle: IT Guru and Linux Sysadmin
description: >- # this means to ignore newlines until "baseurl:"
  Josh Madrone is a network engineer, linux systems administrator, web developer and IT Guru

url: "https://josh.madrone.me" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
    - text: Sample Page
      url: /sample-page

# Edit these details 

author_logo: profile.png
author: Josh Madrone
author_bio: Hi, My Name is Josh Madrone. I love to Code and Design. 
author_email: "josh@madrone.me"
author_location: Humboldt, CA
author_website_url: "http://josh.madrone.me"

author_work_experiences: 
            - company_name: Mattole Salmon Group
              company_logo: mattolesalmon.png
              company_url: http://mattolesalmon.org
              designation: IT Administrator
              description: Managed file server migration to AWS Cloud, manage IT Security, Desktop Linux/macOS/Windows Sysadmin, maintain WordPress Website and Network Administrator
              visibility: true
            - company_name: AllcomOne IT Services LLC
              company_logo: allcomone.png
              company_url: https://allcomone.com
              designation: Network Engineer
              description: Design and implement complex routed LANs & WANs for Schools, Hotels, Small Government & Nongovernment Organizations and Businesses, Enterprise Wireless design & implementation
              visibility: true

author_education_details:
              - college_logo: cr.png
                college_name: College of the Redwoods
                college_url: https://www.redwoods.edu
                college_degree: Network Associate
                description: Certificate
                visibility: true

author_project_details:
              - project_thumbnail: allcomone.png
                project_title: AllcomOne IT Services LLC
                project_description: Technology Made Simple!
                project_url: https://www.allcomone.com
                visibility: true
              - project_thumbnail: photogrammetry.png
                project_title: Photogrammetry - UAV Mapping
                project_description: Making topo maps and digital elevation models with drones
                project_url: https://maps.allcomone.com
                visibility: true

# social links
twitter_username: joshmadrone
github_username:  jmadrone
facebook_username: joshmadrone
instagram_username: joshmadrone


#for comments using disqus
disqus_shortname: joshemeraldmadrone 


# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-49470610-2

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


